### ISSUE TITLE
Pages under http://check.mageia.org/cauldron/ are empty

### ISSUE THREAD

**Issue by shlomif** [guillomovitch/youri-check#3]
Hi @guillomovitch ! Pages like http://check.mageia.org/cauldron/updates.html or http://check.mageia.org/cauldron/shlomif/updates.html have been empty for a while now. This should be fixed. Thanks!

**Comment by guillomovitch** [comment]
I'm just the original author of the code, and I have no access to this host. You'd better check with mageia admins.

**Comment by shlomif** [comment]
On Thu, 07 Mar 2019 21:47:19 +0000 (UTC)
Guillaume Rousse <notifications@github.com> wrote:

> I'm just the original author of the code, and I have no access to this host.
> You'd better check with mageia admins.
> 

ok, thanks, youri-check in mageia seems older, but the one from git master
requires Youri::Factory which I don;t know where to get.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Let’s talk about restores instead of backups - http://is.gd/WatQqu

When Chuck Norris disses your product, it’s not good publicity, even though
you can bet he’ll get the name right.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
